# params.yaml

ModelTrainerParams:
  val_split_size: 0.85
  batch_size: 32
  epochs: 40
  patience: 10
  lr_layer3: 0.000001
  lr_layer4: 0.00001
  lr_fc: 0.0001


label_map:
  0: "surprise"
  1: "fear"
  2: "disgust"
  3: "happiness"
  4: "sadness"
  5: "anger"
  6: "neutral"