# Template for dataset path

artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://huggingface.co/datasets/Revanth214/rafdb_clean/resolve/main/rafdb_org_clean.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test"]

data_transformation:
  root_dir: artifacts/data_transformation
  organized_dir: artifacts/data_ingestion/Organized
  organized_folder: artifacts/data_transformation/Organized

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/Organized/train
  test_data_path: artifacts/data_transformation/Organized/test
  model_path: 'artifacts/model_trainer/best_rafdb_resnet18_enhanced(in_use)'

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/Organized/test
  model_path: 'artifacts/model_trainer/best_rafdb_resnet18_enhanced(in_use)'
  metric_file_name: artifacts/model_evaluation/metrics.json

model_loader:
  root_dir: artifacts/model_loader
  trained_model: https://huggingface.co/Revanth214/emotion_detection_enhanced/resolve/main/best_rafdb_resnet18_enhanced(in_use).pth
  local_model: artifacts/model_loader/best_rafdb_resnet18_enhanced(in_use)
  num_classes: 7

model_processor:
  root_dir: artifacts/model_processor
  image_size: [224, 224]
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]